---
Name: testsession-requestmod
---
TestSessionController:
  extensions:
    - RequestModControllerExtension
Injector:
  RequestProcessor:
    properties:
      filters:
        - '%$RequestModRequestFilter'